version: "3.3"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_SUPERUSER_PASSWORD=admin@123
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_EMAIL=admin@admin.com
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        container_name: celery
        command: celery -A fampay worker -l INFO
        volumes:
            - .:/usr/src/app/
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - DEFAULT_YOUTUBE_API_KEY=AIzaSyBh_21DSkTx_IPZfrifBNhjHYlQZYM7FKs
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        container_name: celery_beat
        command: celery -A fampay beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
            - .:/usr/src/app/
        depends_on:
            - redis
            - celery
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=fampaydb
            - POSTGRES_USER=fampay
            - POSTGRES_PASSWORD=fampay123
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        
volumes:
    pgdata:
